# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env: 
      API: ./src/AppForSEII2526.API/AppForSEII2526.API.csproj
      WEB: ./src/AppForSEII2526.WEB/AppForSEII2526.WEB.csproj
      UT: ./src/AppForSEII2526.UT/AppForSEII2526.UT.csproj
      UIT: ./src/AppForSEII2526.UIT/AppForSEII2526.UIT.csproj

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Restore dependencies
        run: |
          dotnet restore ${{ env.API }}
          dotnet restore ${{ env.WEB }}
          dotnet restore ${{ env.UT }}
          dotnet restore ${{ env.UIT }}
          
      - name: Build the solution 
        run: |
          dotnet build ${{ env.API }}      --configuration Release -- no-restore 
          dotnet build ${{ env.WEB }}      --configuration Release -- no-restore
          dotnet build ${{ env.UT }}       --configuration Release -- no-restore
          dotnet build ${{ env.UIT }}      --configuration Release -- no-restore
          
      - name: Run unit tests with report
        run: dotnet test ${{ env.UT }} --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"

      - name: Upload tests results
        uses: actions/upload-artifact@v4
        with: 
          name: TestResults
          path: ./test/AppForSEII2526.UT/TestResults/TestResults.trx
        with:
